-- Migration: giỏ hàng tài khoản + cột orders.user_id + backfill
-- PostgreSQL. Chạy một lần trên DB đang dùng cho backend deploy.
--
-- Ví dụ:
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f scripts/migrations/20260407_account_orders_cart.sql
--
-- Khắc phục:
-- 1) Thiếu bảng user_cart_items -> /api/account/cart 500
-- 2) Thiếu orders.user_id -> lịch sử đơn khó khớp tài khoản sau migrate

BEGIN;

-- ---------------------------------------------------------------------------
-- 1) Bảng giỏ hàng (khớp BackendWeb/models/UserCartItem.js)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_cart_items (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id integer NOT NULL,
    product_id integer NOT NULL,
    variant_id integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    snapshot jsonb DEFAULT '{}'::jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_cart_items_pkey PRIMARY KEY (id),
    CONSTRAINT user_cart_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_cart_items_user_id
  ON public.user_cart_items USING btree (user_id);

CREATE INDEX IF NOT EXISTS idx_user_cart_items_user_product_variant
  ON public.user_cart_items USING btree (user_id, product_id, variant_id);

COMMENT ON TABLE public.user_cart_items IS 'Giỏ đồng bộ theo user (/api/account/cart)';

-- ---------------------------------------------------------------------------
-- 2) orders.user_id + index + FK + backfill
-- ---------------------------------------------------------------------------
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS user_id integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'orders_user_id_fkey'
      AND conrelid = 'public.orders'::regclass
  ) THEN
    ALTER TABLE ONLY public.orders
      ADD CONSTRAINT orders_user_id_fkey
      FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_orders_user_id
  ON public.orders USING btree (user_id)
  WHERE (user_id IS NOT NULL);

-- Đơn có customer_id -> user từ customers
UPDATE public.orders o
SET user_id = c.user_id
FROM public.customers c
WHERE o.customer_id = c.id
  AND c.user_id IS NOT NULL
  AND (o.user_id IS DISTINCT FROM c.user_id);

-- Khớp email trên đơn với users.email
UPDATE public.orders o
SET user_id = u.id
FROM public.users u
WHERE o.user_id IS NULL
  AND o.customer_email IS NOT NULL
  AND btrim(o.customer_email::text) <> ''
  AND lower(btrim(o.customer_email::text)) = lower(btrim(u.email::text));

-- Khớp SĐT (chỉ số) đơn với customers.phone của user
UPDATE public.orders o
SET user_id = c.user_id
FROM public.customers c
WHERE o.user_id IS NULL
  AND c.user_id IS NOT NULL
  AND c.phone IS NOT NULL
  AND btrim(c.phone::text) <> ''
  AND o.customer_phone IS NOT NULL
  AND btrim(o.customer_phone::text) <> ''
  AND regexp_replace(coalesce(o.customer_phone::text, ''), '[^0-9]', '', 'g') =
      regexp_replace(coalesce(c.phone::text, ''), '[^0-9]', '', 'g')
  AND length(regexp_replace(coalesce(o.customer_phone::text, ''), '[^0-9]', '', 'g')) >= 9;

COMMIT;
